### ISSUE TITLE
code

### ISSUE THREAD

**Issue by flynnamy** [chaofengc/ITER#1]
Hi, any plans to share the code and weights? @chaofengc

**Comment by profile838** [comment]
yes. I am highly interested in this paper too. Your FeMaSR project is one of the best super resolution project. Iter should be better I guess :)

**Comment by chaofengc** [comment]
I appreciate your enthusiasm and curiosity about my work. I am currently working on improving the code and the model, aiming for more robust results. This is a challenging and time-consuming process, and I will share the code as soon as it is finalized. Thank you for your understanding.

**Comment by profile838** [comment]
@chaofengc  any news about progress and info when codes and pretrain model should be available? Thank you very much

**Comment by profile838** [comment]
@chaofengc I see you uploaded models. Is it means that you will publish codes soon? Great

**Comment by chaofengc** [comment]
Thank you for your patience and understanding. While the current performance may not fully meet our expectations, we acknowledge that there has been a significant delay in releasing the code. To address this, we are in the process of finalizing the current version of the code for release. We aim to make it available to you as soon as possible. Your continued support during this process is greatly appreciated.

**Comment by profile838** [comment]
Hey, maybe put a pre-release version in the developer branch of the repository, for us impatient ones to try out the iter :)  Then once you finish optimizing and finalize the code, you can put it in the default release section? Thanks!

**Comment by chaofengc** [comment]
We appreciate your enthusiasm and interest in trying out our method. However, it's important to note that **our paper primarily serves to validate the feasibility of the technical approach.** Currently, **the performance may not meet high expectations**, so there's no need to hurry for a pre-release version. We aim to refine and optimize further before making it available, and anticipate making a more polished version available in the next two weeks. Your patience and understanding in this process are greatly appreciated!

If you are looking for a good performance SR model, please refer to the following repo: https://github.com/Fanghua-Yu/SUPIR

**Comment by profile838** [comment]
Thanks for the reply. I'll definitely wait for the official code. :)

**Comment by Riser-bz** [comment]
你好，文章很nice,可以提供预训练权重参数吗

**Comment by chaofengc** [comment]
They are available in the release section: https://github.com/chaofengc/ITER/releases, and will be downloaded automatically if you tried the codes.

**Comment by Riser-bz** [comment]
File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\container.py", line 219, in forward
    input = module(input)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (struct c10::Half) and bias type (struct c10::BFloat16) should be the same
python-BaseException

**Comment by Riser-bz** [comment]
按readme上跑的，发现以上bug
